using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using FFS.Libraries.StaticEcs;
using StaticMlp.Networking;
using StaticMlp.Networking.Replication;
using UnityCodeGen;
using UnityEditor;
using UnityEngine;

namespace StaticMlp.Editor.ReplicationCodeGen
{
    [Generator]
    public sealed class ReplicatedEventCodeGenerator : ICodeGenerator
    {
        private const string OutputFolder = "Assets/Scripts/StaticMlp/Generated/ReplicationEvents";

        public void Execute(GeneratorContext context)
        {
            context.OverrideFolderPath(OutputFolder);

            var diagnostics = new List<string>();
            var events = TypeCache.GetTypesWithAttribute<ReplicatedEventAttribute>()
                .Where(t => !t.IsAbstract)
                .OrderBy(t => t.FullName, StringComparer.Ordinal)
                .Select(t => CreateEventInfo(t, diagnostics))
                .Where(x => x != null)
                .ToList();

            ValidateDuplicateIds(events, diagnostics);

            context.AddCode("StaticMlp.ReplicatedEvents.CodeGenDiagnostics.Generated.cs", EmitDiagnostics(diagnostics));
            if (diagnostics.Count != 0)
                return;

            context.AddCode("ReplicatedNetworkEventIds.Generated.cs", EmitIds(events));
            context.AddCode("ReplicatedNetworkEventRegistry.Generated.cs", EmitRegistry(events));
        }

        private static EventInfo CreateEventInfo(Type type, List<string> diagnostics)
        {
            var attribute = type.GetCustomAttribute<ReplicatedEventAttribute>();
            if (attribute == null)
                return null;

            if (!type.IsValueType || type.IsEnum)
                diagnostics.Add($"{type.FullName}: replicated event must be a struct.");

            if (!typeof(IEvent).IsAssignableFrom(type))
                diagnostics.Add($"{type.FullName}: replicated event must implement IEvent.");

            var guid = TryReadStaticEcsGuid(type);
            if (!guid.HasValue)
                diagnostics.Add($"{type.FullName}: replicated event must expose a stable StaticEcs guid through IEventConfig<T>.Config().");

            var fields = type.GetFields(BindingFlags.Instance | BindingFlags.Public)
                .Select(f => FieldInfoFor(f, diagnostics))
                .Where(x => x != null)
                .ToList();

            if (fields.Count == 0)
                diagnostics.Add($"{type.FullName}: replicated event has no public replicated fields.");

            return new EventInfo(type, fields, GetEventId(type, guid), attribute.Delivery);
        }

        private static Guid? TryReadStaticEcsGuid(Type type)
        {
            try
            {
                var configMethod = type.GetMethod("Config", BindingFlags.Instance | BindingFlags.Public, null, Type.EmptyTypes, null);
                if (configMethod == null)
                    return null;

                var evt = Activator.CreateInstance(type);
                var config = configMethod.Invoke(evt, Array.Empty<object>());
                var guidField = config?.GetType().GetField("Guid", BindingFlags.Instance | BindingFlags.Public);
                return guidField?.GetValue(config) as Guid?;
            }
            catch
            {
                return null;
            }
        }

        private static EventFieldInfo FieldInfoFor(FieldInfo field, List<string> diagnostics)
        {
            var kind = FieldKind.From(field.FieldType);
            if (!kind.IsSupported)
            {
                diagnostics.Add($"{field.DeclaringType.FullName}.{field.Name}: unsupported replicated event field type {field.FieldType.FullName}.");
                return null;
            }

            return new EventFieldInfo(field, kind);
        }

        private static ushort GetEventId(Type type, Guid? guid)
        {
            var source = guid?.ToString("N") ?? type.FullName;
            var hash = 2166136261u;
            foreach (var ch in source)
            {
                hash ^= ch;
                hash *= 16777619u;
            }

            return (ushort)(1 + hash % 65534);
        }

        private static void ValidateDuplicateIds(List<EventInfo> events, List<string> diagnostics)
        {
            foreach (var group in events.GroupBy(x => x.TypeId).Where(g => g.Count() > 1))
            {
                var names = string.Join(", ", group.Select(x => x.Type.FullName));
                diagnostics.Add($"Duplicate replicated event type id {group.Key}: {names}.");
            }
        }

        private static string EmitDiagnostics(List<string> diagnostics)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("namespace StaticMlp.Networking.Replication.Generated {");
            builder.AppendLine("    public static class ReplicatedEventsCodeGenDiagnostics { }");
            builder.AppendLine("}");
            foreach (var diagnostic in diagnostics)
                builder.AppendLine($"#error {EscapeError(diagnostic)}");
            return builder.ToString();
        }

        private static string EmitIds(List<EventInfo> events)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("namespace StaticMlp.Networking.Replication.Generated {");
            builder.AppendLine("    public static class ReplicatedNetworkEventIds {");
            foreach (var evt in events)
                builder.AppendLine($"        public const ushort {evt.Type.Name} = {evt.TypeId};");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string EmitRegistry(List<EventInfo> events)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("using FFS.Libraries.StaticEcs;");
            builder.AppendLine("using FFS.Libraries.StaticPack;");
            builder.AppendLine("using StaticMlp.Networking;");
            builder.AppendLine("using StaticMlp.Networking.Replication;");
            foreach (var ns in events.Select(x => x.Type.Namespace).Distinct().OrderBy(x => x, StringComparer.Ordinal))
                builder.AppendLine($"using {ns};");
            if (events.Any(x => x.Fields.Any(f => f.Kind.NeedsUnityEngine)))
                builder.AppendLine("using UnityEngine;");
            builder.AppendLine();
            builder.AppendLine("namespace StaticMlp.Networking.Replication.Generated {");
            builder.AppendLine("    public static class ReplicatedNetworkEventRegistry {");
            builder.AppendLine("        public static void RegisterNetworkEvents() {");
            foreach (var evt in events)
            {
                var name = evt.Type.Name;
                builder.AppendLine($"            NetworkEventRegistry.Register<{name}>(");
                builder.AppendLine($"                ReplicatedNetworkEventIds.{name},");
                builder.AppendLine($"                NetDelivery.{evt.Delivery},");
                builder.AppendLine($"                Write{name},");
                builder.AppendLine($"                TryRead{name});");
            }
            builder.AppendLine("        }");
            foreach (var evt in events)
            {
                builder.AppendLine();
                AppendWriteMethod(builder, evt);
                builder.AppendLine();
                AppendReadMethod(builder, evt);
            }
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void AppendWriteMethod(StringBuilder builder, EventInfo evt)
        {
            var name = evt.Type.Name;
            builder.AppendLine($"        private static byte[] Write{name}(in {name} evt) {{");
            builder.AppendLine($"            var writer = BinaryPackWriter.CreateFromPool({EstimateBufferSize(evt)});");
            foreach (var field in evt.Fields)
                AppendWrite(builder, field);
            builder.AppendLine("            var bytes = writer.CopyToBytes();");
            builder.AppendLine("            writer.Dispose();");
            builder.AppendLine("            return bytes;");
            builder.AppendLine("        }");
        }

        private static void AppendReadMethod(StringBuilder builder, EventInfo evt)
        {
            var name = evt.Type.Name;
            builder.AppendLine($"        private static bool TryRead{name}(byte[] payload, out {name} evt) {{");
            builder.AppendLine("            try {");
            builder.AppendLine("                if (payload == null || payload.Length == 0) {");
            builder.AppendLine("                    evt = default;");
            builder.AppendLine("                    return false;");
            builder.AppendLine("                }");
            builder.AppendLine();
            builder.AppendLine("                var reader = new BinaryPackReader(payload, (uint)payload.Length, 0);");
            builder.AppendLine($"                evt = new {name} {{");
            foreach (var field in evt.Fields)
                AppendRead(builder, field);
            builder.AppendLine("                };");
            builder.AppendLine("                return true;");
            builder.AppendLine("            } catch {");
            builder.AppendLine("                evt = default;");
            builder.AppendLine("                return false;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
        }

        private static void AppendWrite(StringBuilder builder, EventFieldInfo field)
        {
            var source = $"evt.{field.Field.Name}";

            switch (field.Kind.Name)
            {
                case "Vector2":
                    builder.AppendLine($"            writer.WriteFloat({source}.x, {source}.y);");
                    break;
                case "Vector3":
                    builder.AppendLine($"            writer.WriteFloat({source}.x, {source}.y, {source}.z);");
                    break;
                case "Quaternion":
                    builder.AppendLine($"            writer.WriteFloat({source}.x, {source}.y, {source}.z, {source}.w);");
                    break;
                case "EntityGID":
                    builder.AppendLine($"            writer.WriteUlong({source}.Raw);");
                    break;
                case "EnumByte":
                    builder.AppendLine($"            writer.WriteByte((byte){source});");
                    break;
                case "EnumUshort":
                    builder.AppendLine($"            writer.WriteUshort((ushort){source});");
                    break;
                case "EnumInt":
                    builder.AppendLine($"            writer.WriteInt((int){source});");
                    break;
                default:
                    builder.AppendLine($"            writer.{field.Kind.WriteMethod}({source});");
                    break;
            }
        }

        private static void AppendRead(StringBuilder builder, EventFieldInfo field)
        {
            var comma = ",";
            var name = field.Field.Name;

            switch (field.Kind.Name)
            {
                case "Vector2":
                    builder.AppendLine($"                    {name} = new Vector2(reader.ReadFloat(), reader.ReadFloat()){comma}");
                    break;
                case "Vector3":
                    builder.AppendLine($"                    {name} = new Vector3(reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat()){comma}");
                    break;
                case "Quaternion":
                    builder.AppendLine($"                    {name} = new Quaternion(reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat()){comma}");
                    break;
                case "EntityGID":
                    builder.AppendLine($"                    {name} = new EntityGID(reader.ReadUlong()){comma}");
                    break;
                case "EnumByte":
                    builder.AppendLine($"                    {name} = ({GetTypeName(field.Field.FieldType)})reader.ReadByte(){comma}");
                    break;
                case "EnumUshort":
                    builder.AppendLine($"                    {name} = ({GetTypeName(field.Field.FieldType)})reader.ReadUshort(){comma}");
                    break;
                case "EnumInt":
                    builder.AppendLine($"                    {name} = ({GetTypeName(field.Field.FieldType)})reader.ReadInt(){comma}");
                    break;
                default:
                    builder.AppendLine($"                    {name} = reader.{field.Kind.ReadMethod}(){comma}");
                    break;
            }
        }

        private static int EstimateBufferSize(EventInfo evt)
        {
            return Math.Max(16, evt.Fields.Sum(x => x.Kind.ByteSize));
        }

        private static string GetTypeName(Type type)
        {
            if (type == typeof(bool)) return "bool";
            if (type == typeof(byte)) return "byte";
            if (type == typeof(sbyte)) return "sbyte";
            if (type == typeof(short)) return "short";
            if (type == typeof(ushort)) return "ushort";
            if (type == typeof(int)) return "int";
            if (type == typeof(uint)) return "uint";
            if (type == typeof(long)) return "long";
            if (type == typeof(ulong)) return "ulong";
            if (type == typeof(float)) return "float";
            return type.Name;
        }

        private static string Camel(string text)
        {
            return string.IsNullOrEmpty(text)
                ? text
                : char.ToLowerInvariant(text[0]) + text.Substring(1);
        }

        private static string EscapeError(string text)
        {
            return text.Replace("\\", "/").Replace("\r", " ").Replace("\n", " ");
        }

        private sealed class EventInfo
        {
            public readonly Type Type;
            public readonly List<EventFieldInfo> Fields;
            public readonly ushort TypeId;
            public readonly NetDelivery Delivery;

            public EventInfo(Type type, List<EventFieldInfo> fields, ushort typeId, NetDelivery delivery)
            {
                Type = type;
                Fields = fields;
                TypeId = typeId;
                Delivery = delivery;
            }
        }

        private sealed class EventFieldInfo
        {
            public readonly FieldInfo Field;
            public readonly FieldKind Kind;

            public EventFieldInfo(FieldInfo field, FieldKind kind)
            {
                Field = field;
                Kind = kind;
            }
        }

        private readonly struct FieldKind
        {
            public readonly string Name;
            public readonly string WriteMethod;
            public readonly string ReadMethod;
            public readonly int ByteSize;
            public readonly bool NeedsUnityEngine;
            public bool IsSupported => Name != null;

            private FieldKind(string name, string writeMethod, string readMethod, int byteSize, bool needsUnityEngine = false)
            {
                Name = name;
                WriteMethod = writeMethod;
                ReadMethod = readMethod;
                ByteSize = byteSize;
                NeedsUnityEngine = needsUnityEngine;
            }

            public static FieldKind From(Type type)
            {
                if (type == typeof(bool)) return new FieldKind("Bool", "WriteBool", "ReadBool", 1);
                if (type == typeof(byte)) return new FieldKind("Byte", "WriteByte", "ReadByte", 1);
                if (type == typeof(sbyte)) return new FieldKind("Sbyte", "WriteSbyte", "ReadSByte", 1);
                if (type == typeof(short)) return new FieldKind("Short", "WriteShort", "ReadShort", 2);
                if (type == typeof(ushort)) return new FieldKind("Ushort", "WriteUshort", "ReadUshort", 2);
                if (type == typeof(int)) return new FieldKind("Int", "WriteInt", "ReadInt", 4);
                if (type == typeof(uint)) return new FieldKind("Uint", "WriteUint", "ReadUint", 4);
                if (type == typeof(long)) return new FieldKind("Long", "WriteLong", "ReadLong", 8);
                if (type == typeof(ulong)) return new FieldKind("Ulong", "WriteUlong", "ReadUlong", 8);
                if (type == typeof(float)) return new FieldKind("Float", "WriteFloat", "ReadFloat", 4);
                if (type == typeof(EntityGID)) return new FieldKind("EntityGID", null, null, 8);
                if (type == typeof(Vector2)) return new FieldKind("Vector2", null, null, 8, needsUnityEngine: true);
                if (type == typeof(Vector3)) return new FieldKind("Vector3", null, null, 12, needsUnityEngine: true);
                if (type == typeof(Quaternion)) return new FieldKind("Quaternion", null, null, 16, needsUnityEngine: true);
                if (type.IsEnum)
                {
                    var underlying = Enum.GetUnderlyingType(type);
                    if (underlying == typeof(byte)) return new FieldKind("EnumByte", null, null, 1);
                    if (underlying == typeof(ushort)) return new FieldKind("EnumUshort", null, null, 2);
                    if (underlying == typeof(int)) return new FieldKind("EnumInt", null, null, 4);
                }
                return default;
            }
        }
    }
}
