// <auto-generated/>
using System;
using FFS.Libraries.StaticEcs;
using FFS.Libraries.StaticPack;
using StaticMlp.Game.Components;
using StaticMlp.Networking;
using UnityEngine;

namespace StaticMlp.Networking.Replication.Generated {
    public static class CharacterNetStateReplication {
        public const ushort TypeId = ReplicatedComponentIds.CharacterNetState;
        public const ReplicationAuthority Authority = ReplicationAuthority.Owner;
        public const NetDelivery Delivery = NetDelivery.UnreliableSequenced;
        public const ushort SendRate = 20;
        public const byte LayoutVersion = 1;

        public static ComponentDelta CreateDelta(EntityGID gid, in CharacterNetState state) {
            var writer = BinaryPackWriter.CreateFromPool(40);
            writer.WriteFloat(Quantize001(state.Position.x), Quantize001(state.Position.y), Quantize001(state.Position.z));
            writer.WriteFloat(Quantize001(state.Velocity.x), Quantize001(state.Velocity.y), Quantize001(state.Velocity.z));
            writer.WriteFloat(state.Rotation.x, state.Rotation.y, state.Rotation.z, state.Rotation.w);
            var bytes = writer.CopyToBytes();
            writer.Dispose();
            return new ComponentDelta(gid, TypeId, bytes);
        }

        public static CharacterNetState Read(byte[] payload) {
            if (payload == null || payload.Length == 0)
                return default;

            var reader = new BinaryPackReader(payload, (uint)payload.Length, 0);
            return new CharacterNetState {
                Position = new Vector3(reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat()),
                Velocity = new Vector3(reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat()),
                Rotation = new Quaternion(reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat()),
            };
        }

        public static void ApplyClientDelta(CW.Entity e, byte[] payload) {
            var next = Read(payload);
            if (e.Has<CharacterNetState>())
                e.Set(new InterpolatedPrevious<CharacterNetState>(e.Read<CharacterNetState>()));
            else
                e.Set(new InterpolatedPrevious<CharacterNetState>(next));

            if (!e.Has<Interpolated<CharacterNetState>>())
                e.Set(new Interpolated<CharacterNetState>(next));

            e.Set(next);
            e.Set(new InterpolatedClock<CharacterNetState> {
                StartedAt = Time.time,
                Duration = SendRate == 0 ? 0f : 1f / SendRate
            });
        }

        public static void Interpolate(in CharacterNetState previous, in CharacterNetState current, ref CharacterNetState interpolated, float alpha) {
            interpolated.Position = Vector3.LerpUnclamped(previous.Position, current.Position, alpha);
            interpolated.Velocity = current.Velocity;
            interpolated.Rotation = Quaternion.Slerp(previous.Rotation, current.Rotation, alpha);
        }

        private static float Quantize001(float value) {
            return (float)Math.Round(value / 0.01f) * 0.01f;
        }
    }
}
