// <auto-generated/>
using System;
using FFS.Libraries.StaticEcs;
using FFS.Libraries.StaticPack;
using StaticMlp.Game.Components.Buildings;
using StaticMlp.Networking;

namespace StaticMlp.Networking.Replication.Generated {
    public static class ConstructionResourcesReplication {
        public const ushort TypeId = ReplicatedComponentIds.ConstructionResources;
        public const ReplicationAuthority Authority = ReplicationAuthority.Server;
        public const NetDelivery Delivery = NetDelivery.ReliableSequenced;
        public const ushort SendRate = 5;
        public const byte LayoutVersion = 1;

        public static ComponentDelta CreateDelta(EntityGID gid, in ConstructionResources state) {
            var writer = BinaryPackWriter.CreateFromPool(16);
            writer.WriteInt(state.WoodRequired);
            writer.WriteInt(state.StoneRequired);
            writer.WriteInt(state.WoodDelivered);
            writer.WriteInt(state.StoneDelivered);
            var bytes = writer.CopyToBytes();
            writer.Dispose();
            return new ComponentDelta(gid, TypeId, bytes);
        }

        public static ConstructionResources Read(byte[] payload) {
            if (payload == null || payload.Length == 0)
                return default;

            var reader = new BinaryPackReader(payload, (uint)payload.Length, 0);
            return new ConstructionResources {
                WoodRequired = reader.ReadInt(),
                StoneRequired = reader.ReadInt(),
                WoodDelivered = reader.ReadInt(),
                StoneDelivered = reader.ReadInt(),
            };
        }
    }
}
