// <auto-generated/>
using System;
using FFS.Libraries.StaticEcs;
using FFS.Libraries.StaticPack;
using StaticMlp.Game.Components.Buildings;
using StaticMlp.Networking;
using UnityEngine;

namespace StaticMlp.Networking.Replication.Generated {
    public static class ConstructionTransformReplication {
        public const ushort TypeId = ReplicatedComponentIds.ConstructionTransform;
        public const ReplicationAuthority Authority = ReplicationAuthority.Server;
        public const NetDelivery Delivery = NetDelivery.ReliableSequenced;
        public const ushort SendRate = 5;
        public const byte LayoutVersion = 1;

        public static ComponentDelta CreateDelta(EntityGID gid, in ConstructionTransform state) {
            var writer = BinaryPackWriter.CreateFromPool(28);
            writer.WriteFloat(Quantize001(state.Position.x), Quantize001(state.Position.y), Quantize001(state.Position.z));
            writer.WriteFloat(state.Rotation.x, state.Rotation.y, state.Rotation.z, state.Rotation.w);
            var bytes = writer.CopyToBytes();
            writer.Dispose();
            return new ComponentDelta(gid, TypeId, bytes);
        }

        public static ConstructionTransform Read(byte[] payload) {
            if (payload == null || payload.Length == 0)
                return default;

            var reader = new BinaryPackReader(payload, (uint)payload.Length, 0);
            return new ConstructionTransform {
                Position = new Vector3(reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat()),
                Rotation = new Quaternion(reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat()),
            };
        }

        private static float Quantize001(float value) {
            return (float)Math.Round(value / 0.01f) * 0.01f;
        }
    }
}
