// <auto-generated/>
using System.Collections.Generic;
using FFS.Libraries.StaticEcs;
using StaticMlp.Networking;
using StaticMlp.Networking.Ownership;
using StaticMlp.Game.Components;
using StaticMlp.Networking.Replication.Generated;

namespace StaticMlp.Networking.Replication {
    public static partial class ReplicationRegistry {
        public static void ApplyDelta(CW.Entity e, ComponentDelta delta) {
            switch (delta.ComponentTypeId) {
                case ReplicatedComponentIds.CharacterNetState:
                    e.Set(CharacterNetStateReplication.Read(delta.Payload));
                    break;
                case ReplicatedComponentIds.NetworkIdentity:
                    e.Set(NetworkIdentityReplication.Read(delta.Payload));
                    break;
            }
        }

        public static void ApplyDelta(SW.Entity e, ComponentDelta delta) {
            switch (delta.ComponentTypeId) {
                case ReplicatedComponentIds.CharacterNetState:
                    e.Set(CharacterNetStateReplication.Read(delta.Payload));
                    break;
                case ReplicatedComponentIds.NetworkIdentity:
                    e.Set(NetworkIdentityReplication.Read(delta.Payload));
                    break;
            }
        }

        public static void CollectDirty(CW.Entity e, NetOutbox outbox, NetworkPeerId peer) {
            if (e.Has<CharacterNetState>() && e.HasChanged<CharacterNetState>())
                outbox.EnqueueComponentDelta(peer, CharacterNetStateReplication.CreateDelta(e.GID, e.Read<CharacterNetState>()), CharacterNetStateReplication.Delivery);
        }

        public static void CollectDirty(SW.Entity e, NetOutbox outbox, NetworkPeerId peer) {
            if (e.Has<CharacterNetState>() && e.HasChanged<CharacterNetState>())
                outbox.EnqueueComponentDelta(peer, CharacterNetStateReplication.CreateDelta(e.GID, e.Read<CharacterNetState>()), CharacterNetStateReplication.Delivery);
        }

        public static void CollectClientOwnedDirty(NetOutbox outbox, NetworkPeerId peer) {
            foreach (var e in CW.Query<All<LocalOwned, NetworkedTag, NetworkIdentity, CharacterNetState>, AllChanged<CharacterNetState>>().Entities())
                outbox.EnqueueComponentDelta(peer, CharacterNetStateReplication.CreateDelta(e.GID, e.Read<CharacterNetState>()), CharacterNetStateReplication.Delivery);
        }

        public static void CollectServerOwnedDirty(NetOutbox outbox, IReadOnlyList<NetworkPeerId> peers) {
            foreach (var e in SW.Query<All<ServerOwned, NetworkedTag, NetworkIdentity, CharacterNetState>, AllChanged<CharacterNetState>>().Entities()) {
                for (var i = 0; i < peers.Count; i++)
                    outbox.EnqueueComponentDelta(peers[i], CharacterNetStateReplication.CreateDelta(e.GID, e.Read<CharacterNetState>()), CharacterNetStateReplication.Delivery);
            }
        }

        public static void CollectInitialState(SW.Entity e, List<ComponentDelta> components) {
            if (e.Has<NetworkIdentity>())
                components.Add(NetworkIdentityReplication.CreateDelta(e.GID, e.Read<NetworkIdentity>()));

            if (e.Has<CharacterNetState>())
                components.Add(CharacterNetStateReplication.CreateDelta(e.GID, e.Read<CharacterNetState>()));
        }

        public static ComponentDelta CreateDelta(EntityGID gid, in CharacterNetState state) {
            return CharacterNetStateReplication.CreateDelta(gid, state);
        }

        public static ComponentDelta CreateDelta(EntityGID gid, in NetworkIdentity identity) {
            return NetworkIdentityReplication.CreateDelta(gid, identity);
        }
    }
}
