// <auto-generated/>
using System.Collections.Generic;
using FFS.Libraries.StaticEcs;
using StaticMlp.Game.Bootstrap;
using StaticMlp.Networking;
using StaticMlp.Networking.Ownership;
using UnityEngine;
using StaticMlp.Game.Components;
using StaticMlp.Game.Components.Buildings;
using StaticMlp.Networking.Replication.Generated;

namespace StaticMlp.Networking.Replication {
    public static partial class ReplicationRegistry {
        public static void ApplyDelta(CW.Entity e, ComponentDelta delta) {
            switch (delta.ComponentTypeId) {
                case ReplicatedComponentIds.ConstructionProgress:
                    e.Set(ConstructionProgressReplication.Read(delta.Payload));
                    break;
                case ReplicatedComponentIds.ConstructionResources:
                    e.Set(ConstructionResourcesReplication.Read(delta.Payload));
                    break;
                case ReplicatedComponentIds.ConstructionSiteState:
                    e.Set(ConstructionSiteStateReplication.Read(delta.Payload));
                    break;
                case ReplicatedComponentIds.ConstructionTransform:
                    e.Set(ConstructionTransformReplication.Read(delta.Payload));
                    break;
                case ReplicatedComponentIds.CharacterNetState:
                    CharacterNetStateReplication.ApplyClientDelta(e, delta.Payload);
                    break;
                case ReplicatedComponentIds.PhysicsCubeNetState:
                    PhysicsCubeNetStateReplication.ApplyClientDelta(e, delta.Payload);
                    break;
                case ReplicatedComponentIds.NetworkIdentity:
                    e.Set(NetworkIdentityReplication.Read(delta.Payload));
                    break;
            }
        }

        public static void ApplyDelta(SW.Entity e, ComponentDelta delta) {
            switch (delta.ComponentTypeId) {
                case ReplicatedComponentIds.ConstructionProgress:
                    e.Set(ConstructionProgressReplication.Read(delta.Payload));
                    break;
                case ReplicatedComponentIds.ConstructionResources:
                    e.Set(ConstructionResourcesReplication.Read(delta.Payload));
                    break;
                case ReplicatedComponentIds.ConstructionSiteState:
                    e.Set(ConstructionSiteStateReplication.Read(delta.Payload));
                    break;
                case ReplicatedComponentIds.ConstructionTransform:
                    e.Set(ConstructionTransformReplication.Read(delta.Payload));
                    break;
                case ReplicatedComponentIds.CharacterNetState:
                    e.Set(CharacterNetStateReplication.Read(delta.Payload));
                    break;
                case ReplicatedComponentIds.PhysicsCubeNetState:
                    e.Set(PhysicsCubeNetStateReplication.Read(delta.Payload));
                    break;
                case ReplicatedComponentIds.NetworkIdentity:
                    e.Set(NetworkIdentityReplication.Read(delta.Payload));
                    break;
            }
        }

        public static void CollectDirty(CW.Entity e, NetOutbox outbox, NetworkPeerId peer) {
            if (e.Has<ConstructionProgress>() && e.HasChanged<ConstructionProgress>())
                outbox.EnqueueComponentDelta(peer, ConstructionProgressReplication.CreateDelta(e.GID, e.Read<ConstructionProgress>()), ConstructionProgressReplication.Delivery);
            if (e.Has<ConstructionResources>() && e.HasChanged<ConstructionResources>())
                outbox.EnqueueComponentDelta(peer, ConstructionResourcesReplication.CreateDelta(e.GID, e.Read<ConstructionResources>()), ConstructionResourcesReplication.Delivery);
            if (e.Has<ConstructionSiteState>() && e.HasChanged<ConstructionSiteState>())
                outbox.EnqueueComponentDelta(peer, ConstructionSiteStateReplication.CreateDelta(e.GID, e.Read<ConstructionSiteState>()), ConstructionSiteStateReplication.Delivery);
            if (e.Has<ConstructionTransform>() && e.HasChanged<ConstructionTransform>())
                outbox.EnqueueComponentDelta(peer, ConstructionTransformReplication.CreateDelta(e.GID, e.Read<ConstructionTransform>()), ConstructionTransformReplication.Delivery);
            if (e.Has<CharacterNetState>() && e.HasChanged<CharacterNetState>())
                outbox.EnqueueComponentDelta(peer, CharacterNetStateReplication.CreateDelta(e.GID, e.Read<CharacterNetState>()), CharacterNetStateReplication.Delivery);
            if (e.Has<PhysicsCubeNetState>() && e.HasChanged<PhysicsCubeNetState>())
                outbox.EnqueueComponentDelta(peer, PhysicsCubeNetStateReplication.CreateDelta(e.GID, e.Read<PhysicsCubeNetState>()), PhysicsCubeNetStateReplication.Delivery);
        }

        public static void CollectDirty(SW.Entity e, NetOutbox outbox, NetworkPeerId peer) {
            if (e.Has<ConstructionProgress>() && e.HasChanged<ConstructionProgress>())
                outbox.EnqueueComponentDelta(peer, ConstructionProgressReplication.CreateDelta(e.GID, e.Read<ConstructionProgress>()), ConstructionProgressReplication.Delivery);
            if (e.Has<ConstructionResources>() && e.HasChanged<ConstructionResources>())
                outbox.EnqueueComponentDelta(peer, ConstructionResourcesReplication.CreateDelta(e.GID, e.Read<ConstructionResources>()), ConstructionResourcesReplication.Delivery);
            if (e.Has<ConstructionSiteState>() && e.HasChanged<ConstructionSiteState>())
                outbox.EnqueueComponentDelta(peer, ConstructionSiteStateReplication.CreateDelta(e.GID, e.Read<ConstructionSiteState>()), ConstructionSiteStateReplication.Delivery);
            if (e.Has<ConstructionTransform>() && e.HasChanged<ConstructionTransform>())
                outbox.EnqueueComponentDelta(peer, ConstructionTransformReplication.CreateDelta(e.GID, e.Read<ConstructionTransform>()), ConstructionTransformReplication.Delivery);
            if (e.Has<CharacterNetState>() && e.HasChanged<CharacterNetState>())
                outbox.EnqueueComponentDelta(peer, CharacterNetStateReplication.CreateDelta(e.GID, e.Read<CharacterNetState>()), CharacterNetStateReplication.Delivery);
            if (e.Has<PhysicsCubeNetState>() && e.HasChanged<PhysicsCubeNetState>())
                outbox.EnqueueComponentDelta(peer, PhysicsCubeNetStateReplication.CreateDelta(e.GID, e.Read<PhysicsCubeNetState>()), PhysicsCubeNetStateReplication.Delivery);
        }

        public static void CollectClientOwnedDirty(NetOutbox outbox, NetworkPeerId peer) {
            foreach (var e in CW.Query<All<LocalOwned, NetworkedTag, NetworkIdentity, ConstructionProgress>, AllChanged<ConstructionProgress>>().Entities())
                outbox.EnqueueComponentDelta(peer, ConstructionProgressReplication.CreateDelta(e.GID, e.Read<ConstructionProgress>()), ConstructionProgressReplication.Delivery);
            foreach (var e in CW.Query<All<LocalOwned, NetworkedTag, NetworkIdentity, ConstructionResources>, AllChanged<ConstructionResources>>().Entities())
                outbox.EnqueueComponentDelta(peer, ConstructionResourcesReplication.CreateDelta(e.GID, e.Read<ConstructionResources>()), ConstructionResourcesReplication.Delivery);
            foreach (var e in CW.Query<All<LocalOwned, NetworkedTag, NetworkIdentity, ConstructionSiteState>, AllChanged<ConstructionSiteState>>().Entities())
                outbox.EnqueueComponentDelta(peer, ConstructionSiteStateReplication.CreateDelta(e.GID, e.Read<ConstructionSiteState>()), ConstructionSiteStateReplication.Delivery);
            foreach (var e in CW.Query<All<LocalOwned, NetworkedTag, NetworkIdentity, ConstructionTransform>, AllChanged<ConstructionTransform>>().Entities())
                outbox.EnqueueComponentDelta(peer, ConstructionTransformReplication.CreateDelta(e.GID, e.Read<ConstructionTransform>()), ConstructionTransformReplication.Delivery);
            foreach (var e in CW.Query<All<LocalOwned, NetworkedTag, NetworkIdentity, CharacterNetState>, AllChanged<CharacterNetState>>().Entities())
                outbox.EnqueueComponentDelta(peer, CharacterNetStateReplication.CreateDelta(e.GID, e.Read<CharacterNetState>()), CharacterNetStateReplication.Delivery);
            foreach (var e in CW.Query<All<LocalOwned, NetworkedTag, NetworkIdentity, PhysicsCubeNetState>, AllChanged<PhysicsCubeNetState>>().Entities())
                outbox.EnqueueComponentDelta(peer, PhysicsCubeNetStateReplication.CreateDelta(e.GID, e.Read<PhysicsCubeNetState>()), PhysicsCubeNetStateReplication.Delivery);
        }

        public static void CollectServerOwnedDirty(NetOutbox outbox, IReadOnlyList<NetworkPeerId> peers) {
            foreach (var e in SW.Query<All<ServerOwned, NetworkedTag, NetworkIdentity, ConstructionProgress>, AllChanged<ConstructionProgress>>().Entities()) {
                for (var i = 0; i < peers.Count; i++)
                    outbox.EnqueueComponentDelta(peers[i], ConstructionProgressReplication.CreateDelta(e.GID, e.Read<ConstructionProgress>()), ConstructionProgressReplication.Delivery);
            }
            foreach (var e in SW.Query<All<ServerOwned, NetworkedTag, NetworkIdentity, ConstructionResources>, AllChanged<ConstructionResources>>().Entities()) {
                for (var i = 0; i < peers.Count; i++)
                    outbox.EnqueueComponentDelta(peers[i], ConstructionResourcesReplication.CreateDelta(e.GID, e.Read<ConstructionResources>()), ConstructionResourcesReplication.Delivery);
            }
            foreach (var e in SW.Query<All<ServerOwned, NetworkedTag, NetworkIdentity, ConstructionSiteState>, AllChanged<ConstructionSiteState>>().Entities()) {
                for (var i = 0; i < peers.Count; i++)
                    outbox.EnqueueComponentDelta(peers[i], ConstructionSiteStateReplication.CreateDelta(e.GID, e.Read<ConstructionSiteState>()), ConstructionSiteStateReplication.Delivery);
            }
            foreach (var e in SW.Query<All<ServerOwned, NetworkedTag, NetworkIdentity, ConstructionTransform>, AllChanged<ConstructionTransform>>().Entities()) {
                for (var i = 0; i < peers.Count; i++)
                    outbox.EnqueueComponentDelta(peers[i], ConstructionTransformReplication.CreateDelta(e.GID, e.Read<ConstructionTransform>()), ConstructionTransformReplication.Delivery);
            }
            foreach (var e in SW.Query<All<ServerOwned, NetworkedTag, NetworkIdentity, CharacterNetState>, AllChanged<CharacterNetState>>().Entities()) {
                for (var i = 0; i < peers.Count; i++)
                    outbox.EnqueueComponentDelta(peers[i], CharacterNetStateReplication.CreateDelta(e.GID, e.Read<CharacterNetState>()), CharacterNetStateReplication.Delivery);
            }
            foreach (var e in SW.Query<All<ServerOwned, NetworkedTag, NetworkIdentity, PhysicsCubeNetState>, AllChanged<PhysicsCubeNetState>>().Entities()) {
                for (var i = 0; i < peers.Count; i++)
                    outbox.EnqueueComponentDelta(peers[i], PhysicsCubeNetStateReplication.CreateDelta(e.GID, e.Read<PhysicsCubeNetState>()), PhysicsCubeNetStateReplication.Delivery);
            }
        }

        public static void CollectInitialState(SW.Entity e, List<ComponentDelta> components) {
            if (e.Has<NetworkIdentity>())
                components.Add(NetworkIdentityReplication.CreateDelta(e.GID, e.Read<NetworkIdentity>()));

            if (e.Has<ConstructionProgress>())
                components.Add(ConstructionProgressReplication.CreateDelta(e.GID, e.Read<ConstructionProgress>()));

            if (e.Has<ConstructionResources>())
                components.Add(ConstructionResourcesReplication.CreateDelta(e.GID, e.Read<ConstructionResources>()));

            if (e.Has<ConstructionSiteState>())
                components.Add(ConstructionSiteStateReplication.CreateDelta(e.GID, e.Read<ConstructionSiteState>()));

            if (e.Has<ConstructionTransform>())
                components.Add(ConstructionTransformReplication.CreateDelta(e.GID, e.Read<ConstructionTransform>()));

            if (e.Has<CharacterNetState>())
                components.Add(CharacterNetStateReplication.CreateDelta(e.GID, e.Read<CharacterNetState>()));

            if (e.Has<PhysicsCubeNetState>())
                components.Add(PhysicsCubeNetStateReplication.CreateDelta(e.GID, e.Read<PhysicsCubeNetState>()));
        }

        public static void RegisterClientCoreGeneratedTypes() {
            CW.Types()
                .Component<Interpolated<CharacterNetState>>()
                .Component<InterpolatedPrevious<CharacterNetState>>()
                .Component<InterpolatedClock<CharacterNetState>>()
                .Component<Interpolated<PhysicsCubeNetState>>()
                .Component<InterpolatedPrevious<PhysicsCubeNetState>>()
                .Component<InterpolatedClock<PhysicsCubeNetState>>();
        }

        public static void RegisterClientCoreInterpolationSystems(ClientCoreSystemsBuilder systems) {
            systems.Add(new ReplicatedInterpolationSystem<CharacterNetState>(CharacterNetStateReplication.Interpolate), GameplaySystemOrder.ClientPresentation);
            systems.Add(new ReplicatedInterpolationSystem<PhysicsCubeNetState>(PhysicsCubeNetStateReplication.Interpolate), GameplaySystemOrder.ClientPresentation);
        }

        public static void InitializeClientCoreInterpolatedState(CW.Entity e) {
            if (e.Has<CharacterNetState>() && !e.Has<Interpolated<CharacterNetState>>()) {
                var state = e.Read<CharacterNetState>();
                e.Set(new Interpolated<CharacterNetState>(state));
                e.Set(new InterpolatedPrevious<CharacterNetState>(state));
                e.Set(new InterpolatedClock<CharacterNetState> {
                    StartedAt = Time.time,
                    Duration = CharacterNetStateReplication.SendRate == 0 ? 0f : 1f / CharacterNetStateReplication.SendRate
                });
            }
            if (e.Has<PhysicsCubeNetState>() && !e.Has<Interpolated<PhysicsCubeNetState>>()) {
                var state = e.Read<PhysicsCubeNetState>();
                e.Set(new Interpolated<PhysicsCubeNetState>(state));
                e.Set(new InterpolatedPrevious<PhysicsCubeNetState>(state));
                e.Set(new InterpolatedClock<PhysicsCubeNetState> {
                    StartedAt = Time.time,
                    Duration = PhysicsCubeNetStateReplication.SendRate == 0 ? 0f : 1f / PhysicsCubeNetStateReplication.SendRate
                });
            }
        }

        public static ComponentDelta CreateDelta(EntityGID gid, in CharacterNetState state) {
            return CharacterNetStateReplication.CreateDelta(gid, state);
        }

        public static ComponentDelta CreateDelta(EntityGID gid, in ConstructionProgress state) {
            return ConstructionProgressReplication.CreateDelta(gid, state);
        }

        public static ComponentDelta CreateDelta(EntityGID gid, in ConstructionResources state) {
            return ConstructionResourcesReplication.CreateDelta(gid, state);
        }

        public static ComponentDelta CreateDelta(EntityGID gid, in ConstructionSiteState state) {
            return ConstructionSiteStateReplication.CreateDelta(gid, state);
        }

        public static ComponentDelta CreateDelta(EntityGID gid, in ConstructionTransform state) {
            return ConstructionTransformReplication.CreateDelta(gid, state);
        }

        public static ComponentDelta CreateDelta(EntityGID gid, in PhysicsCubeNetState state) {
            return PhysicsCubeNetStateReplication.CreateDelta(gid, state);
        }

        public static ComponentDelta CreateDelta(EntityGID gid, in NetworkIdentity identity) {
            return NetworkIdentityReplication.CreateDelta(gid, identity);
        }
    }
}
